# # Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.
#
# Usage:
#
#  make_group(group-name source1 source2 ...)
#
macro(make_group GROUPNAME)
  if (ENABLE_GROUPS)
    string(TOLOWER ${GROUPNAME} group_name_lc)
    set(group_file_name ${CMAKE_CURRENT_BINARY_DIR}/${group_name_lc}.c)
    set(${GROUPNAME} ${group_file_name})

    #TODO:
    # Split C/C++ files to separate groups
    # Create multiple groups for large number of sources.
    # Generate source dependencies.
    file(WRITE ${group_file_name} "//Autogenerated \n")
    foreach(file ${ARGN})
      file(APPEND ${group_file_name}
          "#include \"${CMAKE_CURRENT_SOURCE_DIR}/${file}\"\n")
    endforeach()
  else ()
    set(${GROUPNAME} ${ARGN})
  endif ()
endmacro()